min_version = '2025.10'

#
# -- fancy stuff --
#
[tools]
usage = "latest"
starship = "latest"
bat = "latest"
neovim = "latest"
tmux = "3.6a"
fzf = "latest"
eza = "latest"
fd = "latest"
ripgrep = "latest"
zoxide = "latest"
btop = "latest"
difftastic = "latest"
shfmt = "latest"
fastfetch = "latest"

#
# -- devops stuff --
#
task = "latest"
kubectx = "latest"
kubens = "latest"
sops = "latest"
age = "latest"
terragrunt = "latest"
# flux2 = "2.7"
kubectl = "1.33"
k9s = "latest"

# vault = "1.20"
# terraform = "1.13"
# helm = "3.19"
# opentofu = "1.10"
# jq = "1.8"
#

# -- packaging stuff --
#
pipx = "latest"

#
# -- programming languages --
#
node = "latest"
python = "3.14"
go = "latest"
rust = "stable"

[env]
SOPS_EDITOR = "nvim"
